### ISSUE TITLE
Repl this? (by aenbar)

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/looping-loop#2]
@SophieDeBenedetto 

Adam left a comment on the 000 repo:

This might be better to do in a repl. Or just add a test? feels weird to have labs without tests.

**Comment by SophieDeBenedetto** [comment]
Hi @markedwardmurray and @aenbar: this can't be a REPL because REPL doesn't support testing for `puts`. I hesitate to use a test because this challenge has them create an infinite loop and then the test would just hang there/be frozen. This is their first intro to looping so don't want to add more advanced concepts like breaking yet.

**Comment by matbalez** [comment]
@ktravers is the lack of support for `puts` a hard limitation or is there a way to work around this?

**Comment by loganhasson** [comment]
@matbalez @ktravers this can be added, though it'd probably need to be a new assertion, like `assert_output` or something. can probably use some of the old custom methods that are hanging around some of the older labs that do magic-y stuff to grab from stdout.

**Comment by matbalez** [comment]
i think it would be worth adding this support

**Comment by matbalez** [comment]
Raised ticket: https://github.com/flatiron-labs/ironboard/issues/2783

**Comment by AnnJohn** [comment]
Closing issue
