### ISSUE TITLE
Broken exercise

### ISSUE THREAD

**Issue by vibraniumforge** [learn-co-curriculum/looping-loop#23]
This exercise does not work. Can someone please fix this?

**Comment by vibraniumforge** [comment]
Hi,

That lab does not work right. I used the "Ask a question" for help, and
that person was aware of it.

I cannot get credit for that exercise, and I always get a warning whenever
I open the IDE about it.

I think it needs a "Open IDE" button. Now it only has a "Sandbox button" .

Then I can do the exercise and get the green circle.




While we are on the subject, passing the "Building nested Hashes " lab
won't let you pass unless you edit the testing file. There is no
information about this on the page. I had to ask a question about this again

Thanks

Greg

**Comment by drakeltheryuujin** [comment]
Hi @vibraniumforge,

Thanks for the reply. It sounds like it is an issue with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)) and not the curriculum itself. Make sure to submit a bug report to bugs@learn.co. 

As for the other lab, if there is an issue with the tests, if you have not already done so, please make sure that the issue has been raised there so that it can be tracked and fixed by the Curriculum Team.

Thanks! 💙
